const execa = require('execa')
const fs = require('fs')
const path = require('path')
const { version } = require('../../package.json')

const pm2 = path.join(require.resolve('pm2', { paths: [path.join(__dirname, 'node_modules')] }), '../../.bin/pm2')

/**
 * Finds the path to a binary by checking multiple locations
 * @param {string} networkDir - The network directory
 * @param {string} binaryName - Name of the binary (e.g., 'nyc', 'c8')
 * @returns {string} Path to the binary
 */
const findBinaryPath = (networkDir, binaryName) => {
  // Possible locations to check, in order of preference
  const possibleLocations = [
    // Project root node_modules
    path.resolve(process.cwd(), 'node_modules/.bin', binaryName),
    // Network directory node_modules
    path.resolve(networkDir, 'node_modules/.bin', binaryName),
    // CLI tool's node_modules
    path.resolve(__dirname, '../../../node_modules/.bin', binaryName),
    // Global installation (just use the binary name)
    binaryName
  ]
  
  // Check each location and return the first one that exists
  for (const location of possibleLocations) {
    try {
      // For local paths, check if file exists
      if (location.includes('node_modules')) {
        if (fs.existsSync(location)) {
          console.log(`Found ${binaryName} at: ${location}`)
          return location
        }
      } else {
        // For global binary, try to resolve it using 'which'
        try {
          const { stdout } = execa.sync('which', [location])
          if (stdout) {
            console.log(`Found global ${binaryName} at: ${stdout.trim()}`)
            return stdout.trim()
          }
        } catch (err) {
          // which command failed, continue to next location
        }
      }
    } catch (err) {
      // Continue to next location
    }
  }
  
  // If we get here, we couldn't find the binary - use global name as fallback
  console.warn(`Warning: Could not find ${binaryName} in expected locations. Falling back to global installation.`)
  return binaryName
}

const pm2Start = async (networkDir, script, name, env = {}, pm2Args = [], coverageSettings = null) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  
  let execaCmd = ''
  const parsedPm2Args = pm2Args.map((arg) => arg.split('pm2')[1] || arg).join(' ')
  
  if (coverageSettings) {
    try {
      const coverageTool = coverageSettings.tool.toLowerCase()
      const outputDir = path.join(networkDir, coverageSettings.outputDir || 'coverage')
      
      // Ensure coverage output directory exists
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true })
      }
      
      // Create a wrapper script that will invoke the coverage tool
      const wrapperScript = path.join(networkDir, `.nyc-wrapper-${name}.sh`)
      
      let wrapperContent = `#!/bin/bash\n\n# Wrapper script generated by Shardus CLI for coverage\n\n`
      
      // Add debugging to help troubleshoot environment variable issues
      wrapperContent += `# === Environment Variable Debugging ===\n`
      wrapperContent += `echo "=== Starting coverage for ${name} ==="\n`
      wrapperContent += `echo "Wrapper script: ${wrapperScript}"\n`
      wrapperContent += `echo "Current directory: $(pwd)"\n`
      wrapperContent += `echo "Script to run: ${script}"\n\n`
      
      // Option to dump all environment variables for debugging
      wrapperContent += `# Uncomment to see all environment variables\n`
      wrapperContent += `# echo "=== All Environment Variables ==="\n`
      wrapperContent += `# env | sort\n\n`
      
      // Add env diagnostic section to debug critical variables
      wrapperContent += `# Diagnostic output for critical environment variables\n`
      wrapperContent += `echo "=== Critical Environment Variables ==="\n`
      wrapperContent += `echo "BASE_DIR: $BASE_DIR"\n`
      wrapperContent += `echo "NODE_ENV: $NODE_ENV"\n`
      wrapperContent += `echo "LOAD_JSON_CONFIGS: $LOAD_JSON_CONFIGS"\n`
      wrapperContent += `echo "ARCHIVER_INFO: $ARCHIVER_INFO"\n`
      wrapperContent += `echo "==================================="\n\n`
      
      // 1. First, add any custom environment variables from the coverage config (highest priority)
      if (coverageSettings.env) {
        wrapperContent += `# Environment variables from coverage configuration\n`
        Object.entries(coverageSettings.env).forEach(([key, value]) => {
          wrapperContent += `export ${key}="${value}"\n`
        })
        wrapperContent += `\n`
      }
      
      // 2. Next, add all environment variables passed to pm2Start (second priority)
      if (env && Object.keys(env).length > 0) {
        wrapperContent += `# Environment variables passed directly to pm2Start\n`
        Object.entries(env).forEach(([key, value]) => {
          // Skip if already defined in coverage.env
          if (!coverageSettings.env || !coverageSettings.env[key]) {
            wrapperContent += `export ${key}="${value}"\n`
          }
        })
        wrapperContent += `\n`
      }
      
      // 3. Finally, add crucial environment variables from process.env (lowest priority)
      wrapperContent += `# Important environment variables from the current process\n`
      
      // Common Shardus and Node.js environment variables to preserve
      const commonEnvVars = [
        'NODE_ENV', 'BASE_DIR', 'LOAD_JSON_CONFIGS', 'LOG_LEVEL', 'DEBUG', 
        'PATH', 'NODE_PATH', 'ARCHIVER_INFO', 'ARCHIVER_PORT', 'ARCHIVER_DB',
        'VALIDATOR_KEY', 'OPERATOR_KEY', 'NETWORK_ID', 'CHAIN_ID', 
        'APP_SEEDLIST', 'APP_MONITOR', 'APP_IP', 'EXISTING_ARCHIVERS',
        'VERBOSE_LOGS', 'DEBUG_TRACE'
      ]
      
      // Add the common environment variables from the process if they exist
      commonEnvVars.forEach(varName => {
        // Only add if not already defined in higher priority sources
        if (process.env[varName] && 
            (!env || !env[varName]) && 
            (!coverageSettings.env || !coverageSettings.env[varName])) {
          wrapperContent += `export ${varName}="${process.env[varName]}"\n`
        }
      })
      
      // Add a fallback section that passes through any environment variable starting with common prefixes
      wrapperContent += `\n# Additional environment variables with common prefixes\n`
      Object.entries(process.env).forEach(([key, value]) => {
        const prefixes = ['SHARDUS_', 'SHARDEUM_', 'NODE_', 'APP_', 'ARCHIVER_', 'VALIDATOR_']
        if (prefixes.some(prefix => key.startsWith(prefix)) &&
            (!env || !env[key]) && 
            (!coverageSettings.env || !coverageSettings.env[key]) &&
            !commonEnvVars.includes(key)) {
          wrapperContent += `export ${key}="${value}"\n`
        }
      })
      
      wrapperContent += `\n`
      
      // Add the coverage command with all arguments
      if (coverageTool === 'istanbul' || coverageTool === 'nyc') {
        // Find the nyc binary
        let nycPath = 'nyc'
        try {
          const nycBinResult = await execa.command('which nyc')
          if (nycBinResult.stdout.trim()) {
            nycPath = nycBinResult.stdout.trim()
          }
        } catch (e) {
          // If 'which nyc' fails, use default 'nyc' and hope it's in PATH
          console.log('Warning: Could not find nyc binary, using default "nyc"')
        }
        
        wrapperContent += `# Execute with Istanbul/NYC coverage\n`
        let nycCommand = `${nycPath} --reporter=lcov --reporter=text --report-dir="${outputDir}/${name}"`
        
        // Add include flags for dependencies if configured
        if (coverageSettings.includeDependencies && coverageSettings.includeDependencies.length > 0) {
          wrapperContent += `# Including coverage for dependencies: ${coverageSettings.includeDependencies.join(', ')}\n`
          coverageSettings.includeDependencies.forEach(dep => {
            nycCommand += ` --include="${dep}"`
          })
        }
        
        wrapperContent += `${nycCommand} node ${script} "$@"\n`
      } else if (coverageTool === 'c8') {
        // Find the c8 binary
        let c8Path = 'c8'
        try {
          const c8BinResult = await execa.command('which c8')
          if (c8BinResult.stdout.trim()) {
            c8Path = c8BinResult.stdout.trim()
          }
        } catch (e) {
          // If 'which c8' fails, use default 'c8' and hope it's in PATH
          console.log('Warning: Could not find c8 binary, using default "c8"')
        }
        
        wrapperContent += `# Execute with C8 coverage\n`
        let c8Command = `${c8Path} --reporter=lcov --reporter=text --report-dir="${outputDir}/${name}"`
        
        // Add include flags for dependencies if configured
        if (coverageSettings.includeDependencies && coverageSettings.includeDependencies.length > 0) {
          wrapperContent += `# Including coverage for dependencies: ${coverageSettings.includeDependencies.join(', ')}\n`
          coverageSettings.includeDependencies.forEach(dep => {
            c8Command += ` --include="${dep}"`
          })
        }
        
        wrapperContent += `${c8Command} node ${script} "$@"\n`
      } else {
        throw new Error(`Unsupported coverage tool: ${coverageTool}`)
      }
      
      // Log the wrapper script path to make it easier to find for debugging
      console.log(`Created coverage wrapper script at: ${wrapperScript}`)
      
      // Write and make executable
      fs.writeFileSync(wrapperScript, wrapperContent)
      fs.chmodSync(wrapperScript, '755')
      
      // Use the wrapper script instead of direct execution
      script = wrapperScript
      pm2Args = []
    } catch (error) {
      console.error('Error setting up coverage:', error)
      // Fall back to normal execution without coverage
      console.log('Falling back to normal execution without coverage')
    }
  }
  
  execaCmd = `${pm2} start ${script} --name="${name}" ${parsedPm2Args}`
  
  console.log('pm2Start', execaCmd)
  await execa.command(execaCmd, { cwd: networkDir, env, stdio: [0, 1, 2] })
}

const pm2Restart = async (networkDir, name, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  // const parsedPm2Args = pm2Args.map((arg) => arg.split('pm2')[1] || arg).join(' ')
  const execaCmd = `${pm2} restart ${name} --update-env`
  console.log('pm2Restart', execaCmd, env)
  await execa.command(execaCmd, { cwd: networkDir, env, stdio: [0, 1, 2] })
}

const pm2Stop = async (networkDir, arg, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  await execa.command(`${pm2} stop ${arg}`, {
    cwd: networkDir,
    env,
    stdio: [0, 1, 2],
  })
}

const pm2Kill = async (networkDir, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  await execa.command(`${pm2} kill`, { cwd: networkDir, env, stdio: [0, 1, 2] })
}

const pm2Reset = async (arg, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  await execa.command(`${pm2} reset ${arg}`, { env, stdio: [0, 1, 2] })
}

const pm2Del = async (arg, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  await execa.command(`${pm2} del ${arg}`, { env, stdio: [0, 1, 2] })
}

const pm2List = async (networkDir, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  await execa.command(`${pm2} list`, { cwd: networkDir, env, stdio: [0, 1, 2] })
}

const pm2InstallRotateLog = async (networkDir, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  await execa.command(`${pm2} install pm2-logrotate`, {
    cwd: networkDir,
    env,
    stdio: [0, 1, 2],
  })
}

const pm2SetRotateLog = async (networkDir, maxSizeMb = 10, retain = 10, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  await execa.command(`${pm2} set pm2-logrotate:max_size ${maxSizeMb}M`, {
    cwd: networkDir,
    env,
    stdio: [0, 1, 2],
  })
  await execa.command(`${pm2} set pm2-logrotate:retain ${retain}`, {
    cwd: networkDir,
    env,
    stdio: [0, 1, 2],
  })
  // Displays PM2s conf variables
  await execa.command(`${pm2} conf`, { cwd: networkDir, env, stdio: [0, 1, 2] })
}

const pm2Exec = async (networkDir, arg, env = {}) => {
  env.PM2_HOME = path.join(networkDir, '.pm2/')
  await execa.command(`${pm2} ${arg}`, {
    cwd: networkDir,
    env,
    stdio: [0, 1, 2],
  })
}

const checkVersion = (v1, v2) => {
  let major1 = v1.split('.')[0]
  let major2 = v2.split('.')[0]
  if (major1 !== major2) {
    return false
  }
  return true
}

const checkNetworkFolder = (networkPath, silent) => {
  // Return false if networkPath doesn't exist
  if (fs.existsSync(networkPath) === false) {
    if (!silent) console.error(`ERROR: Unable to find network directory ${networkPath}`)
    return false
  }

  const networkConfigPath = path.join(networkPath, 'network-config.json')

  // Return false if network-config.json is not found in networkPath
  if (fs.existsSync(networkConfigPath) === false) {
    if (!silent) console.error(`ERROR: Cannot find a valid network-config.json file in ${networkPath}.`)
    return false
  }

  // Attempt to parse network-config.json
  let networkConfig
  try {
    networkConfig = JSON.parse(fs.readFileSync(networkConfigPath))
  } catch (err) {
    if (!silent) console.error(`ERROR: Error parsing network-config.json: ${err.message}`)
    return false
  }

  // Return false if our shardus-network tool version is not compatible with the one that created the network
  if (checkVersion(networkConfig['shardus-network-version'], version) === false) {
    if (!silent) console.error('ERROR: Network configuration was created with a different major version of shardus network tool.')
    return false
  }

  return true
}

const setNetworkDirOrErr = (dir) => {
  // Set networkDir to CWD if dir is not passed
  let networkDir = path.join(process.cwd(), dir || '')

  // Set networkDir to networkDir/instances if networkDir fails check
  if (checkNetworkFolder(networkDir) === false) {
    networkDir = path.join(networkDir, 'instances')

    // Error if networkDir/instances fails check too
    console.log(`Checking ${networkDir}...`)
    if (checkNetworkFolder(networkDir) === false) {
      throw 'Could not find network-config.json'
    }
  }

  // Return networkDir if alls good
  return networkDir
}

const sleep = (ms) => {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

module.exports = {
  pm2Start,
  pm2Restart,
  pm2Stop,
  pm2Kill,
  pm2Reset,
  pm2Del,
  pm2List,
  pm2InstallRotateLog,
  pm2SetRotateLog,
  pm2Exec,
  checkNetworkFolder,
  setNetworkDirOrErr,
  sleep
}
